### El objetivo de esta notebook es extraer las coordenadas de los locales bailables en CABA y sus principales características

In [329]:
import numpy as np
import pandas as pd

In [330]:
locales_bailables = pd.read_csv('../Data/locales-bailables.csv')
locales_bailables.sample(3)

,longitud,latitud,numero_registro,nombre,calle,numero,direccion_normalizada,numero_expediente,capacidad,clase,...,numero_disp_de_rechazo,fecha_disposicion_de_rechazo,numero_disposicion_de_recalculo_capacidad,fecha_disposicion_de_capacidad,fecha_de_entrega_nueva_revalida,vencimiento,barrio,comuna,codigo_postal,codigo_postal_argentino
104,-58.436228,-34.586604,105.0,INPUT,AV. JUAN B. JUSTO,1658,AV. JUAN B. JUSTO 1658,3570271/19,742 personas,C,...,NaN,NaN,103,2010-08-20 00:00:00,2019-10-08,2019-12-28,Palermo,Comuna 14,1414.0,C1414CWS
151,-58.436459,-34.552903,151.0,MINA,SUCRE,646/8,SUCRE 646,23211628/19,402 personas,C,...,NaN,NaN,81,2019-08-28 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,C1428DUB
9,-58.391179,-34.605601,10.0,MALUCO \nBELEZA,SARMIENTO,1728,SARMIENTO 1728,3944043/19,1076 personas,"""C""",...,NaN,NaN,92,2006-07-11 00:00:00,NaN,NaN,San Nicolas,Comuna 1,1042.0,C1042ABH

In [331]:
locales_bailables.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 25 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   longitud                                   135 non-null    float64
 1   latitud                                    135 non-null    float64
 2   numero_registro                            160 non-null    float64
 3   nombre                                     160 non-null    object
 4   calle                                      161 non-null    object
 5   numero                                     159 non-null    object
 6   direccion_normalizada                      161 non-null    object
 7   numero_expediente                          160 non-null    object
 8   capacidad                                  159 non-null    object
 9   clase                                      159 non-null    object
 10  estado                                     160 non-null    object
 11  disposicion                                160 non-null    float64
 12  fecha_disp_inscripcion                     160 non-null    object
 13  numero_dips                                153 non-null    float64
 14  fecha_disp_re_inscripcion                  153 non-null    object
 15  numero_disp_de_rechazo                     5 non-null      object
 16  fecha_disposicion_de_rechazo               5 non-null      object
 17  numero_disposicion_de_recalculo_capacidad  158 non-null    object
 18  fecha_disposicion_de_capacidad             158 non-null    object
 19  fecha_de_entrega_nueva_revalida            78 non-null     object
 20  vencimiento                                78 non-null     object
 21  barrio                                     154 non-null    object
 22  comuna                                     155 non-null    object
 23  codigo_postal                              155 non-null    float64
 24  codigo_postal_argentino                    146 non-null    object
dtypes: float64(6), object(19)
memory usage: 31.6+ KB

In [332]:
# Creamos una columna que contenga la latitud y longitud simultáneamente
locales_bailables['lat-lon'] = list(zip(locales_bailables.latitud, locales_bailables.longitud))
locales_bailables.columns

Index(['longitud', 'latitud', 'numero_registro', 'nombre', 'calle', 'numero',
       'direccion_normalizada', 'numero_expediente', 'capacidad', 'clase',
       'estado', 'disposicion', 'fecha_disp_inscripcion', 'numero_dips',
       'fecha_disp_re_inscripcion', 'numero_disp_de_rechazo',
       'fecha_disposicion_de_rechazo',
       'numero_disposicion_de_recalculo_capacidad',
       'fecha_disposicion_de_capacidad', 'fecha_de_entrega_nueva_revalida',
       'vencimiento', 'barrio', 'comuna', 'codigo_postal',
       'codigo_postal_argentino', 'lat-lon'],
      dtype='object')

In [344]:
# Renombro la columna capacidad
locales_bailables_1 = locales_bailables_1.rename(columns={'capacidad':'capacidad_personas', 'direccion_normalizada':'direccion'})
locales_bailables_1

,numero_registro,direccion,lat-lon,capacidad_personas
0,1.0,RIOBAMBA 345,"(-34.605027, -58.39375)",428 personas
1,2.0,ESMERALDA 1040,"(-34.596003, -58.37851)",408 personas
2,3.0,PERU 342,"(-34.612002000000004, -58.374727)",901 personas
3,4.0,SARMIENTO 1656,"(-34.605531, -58.390154)",1372 personas
4,5.0,LAVALLE 343,"(-34.60195, -58.371747)",880 personas
...,...,...,...,...
156,156.0,AV. RAFAEL \nOBLIGADO 1221,"(nan, nan)",1195 personas
157,157.0,AV. JUAN B. JUSTO 1579,"(-34.585813, -58.435554)",376 personas
158,158.0,AV. RIVADAVIA 10919,"(-34.639008000000004, -58.517858999999994)",1852 personas
159,159.0,AV. RAFAEL \nOBLIGADO 6201,"(nan, nan)",956 personas
160,160.0,AV. CORDOBA 5208,"(-34.59016, -58.436476)",505 personas

In [345]:
# Chequeo antes la presencia de nulos en la columna "capacidad_personas" y los viusualizo en el df original
mask_nulls_capacidad = locales_bailables_1['capacidad_personas'].isnull()
locales_bailables.loc[mask_nulls_capacidad]

,longitud,latitud,numero_registro,nombre,calle,numero,direccion_normalizada,numero_expediente,capacidad,clase,...,fecha_disposicion_de_rechazo,numero_disposicion_de_recalculo_capacidad,fecha_disposicion_de_capacidad,fecha_de_entrega_nueva_revalida,vencimiento,barrio,comuna,codigo_postal,codigo_postal_argentino,lat-lon
46,-58.386061,-34.605278,47.0,SALON AGUSTEO,SARMIENTO,1374,SARMIENTO 1374,10587/05,NaN,ART 1º,...,NaN,NaN,NaN,NaN,NaN,San Nicolas,Comuna 1,1041.0,C1041ABB,"(-34.605278000000006, -58.386061)"
123,-58.436026,-34.586454,NaN,NaN,Av. J. B. JUSTO,1634,Av. J. B. JUSTO 1634,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Palermo,Comuna 14,1414.0,C1414CWS,"(-34.586453999999996, -58.436026)"

In [346]:
# Al haber tan poca información de estos casos en el df original, optamos por desecharlas
locales_bailables_2 = locales_bailables_1.dropna(axis=0)
locales_bailables_2.capacidad_personas.isnull().value_counts()

False    159
Name: capacidad_personas, dtype: int64

In [340]:
# Vamos a quedarnos solo con las columnas más relevantes para nuestro trabajo
locales_bailables_1 = locales_bailables.loc[:,['numero_registro', 'direccion_normalizada','lat-lon','capacidad']]
# Explicar por qué utilizamos la columna "capacidad" y no "clase" (?
locales_bailables_1.sample(3)

,numero_registro,direccion_normalizada,lat-lon,capacidad
63,64.0,RECONQUISTA 876,"(-34.597627, -58.372953)",208 personas
72,73.0,AV JUAN B. JUSTO 1625,"(-34.586175, -58.43604499999999)",572 personas
138,138.0,BALCARCE 605,"(-34.614905, -58.370716)",425 personas

In [1]:
# Le saco las caracteres para luego modificar hacerla de tipo 'int'
locales_bailables_1['capacidad_personas'] = locales_bailables_1.capacidad_personas.str.strip('personas ')
locales_bailables_1

NameError: name 'locales_bailables_1' is not defined

In [342]:
# Chequeo antes la presencia de nulos en la columna "lat-lon" y los viusualizo en el df original
mask_lb_null = (locales_bailables.longitud.isnull() | locales_bailables.latitud.isnull())

locales_bailables[mask_lb_null]

,longitud,latitud,numero_registro,nombre,calle,numero,direccion_normalizada,numero_expediente,capacidad,clase,...,fecha_disposicion_de_rechazo,numero_disposicion_de_recalculo_capacidad,fecha_disposicion_de_capacidad,fecha_de_entrega_nueva_revalida,vencimiento,barrio,comuna,codigo_postal,codigo_postal_argentino,lat-lon
10,NaN,NaN,11.0,XEL - HA,AV SAN M ARTÍN,6628,AV SAN M ARTÍN 6628,6128100/19,692 personas,"""C""",...,NaN,70,2005-06-10 00:00:00,2019-11-20,2020-02-10,Villa Devoto,Comuna 11,1419.0,C1419ICQ,"(nan, nan)"
37,NaN,NaN,38.0,CAIX,R. OBLIGADO \nY SALGUERO,sin nº,R. OBLIGADO \nY SALGUERO,4960926/19,1764 personas,"""C""",...,NaN,134,2005-09-28 00:00:00,2019-11-14,2020-02-15,NaN,NaN,NaN,NaN,"(nan, nan)"
43,NaN,NaN,44.0,MANDARINE,R. OBLIGADO \nY SARMIENTO,sin nº,R. OBLIGADO \nY SARMIENTO,2335460/19,1613 personas,"""C""",...,NaN,38,2009-03-23 00:00:00,2019-11-22,2020-02-21,NaN,NaN,NaN,NaN,"(nan, nan)"
54,NaN,NaN,55.0,CLUB 74,FIGUEROA \nALCORTA,7474,FIGUEROA \nALCORTA 7474,10836/05,180 personas,"""B""",...,NaN,76,2006-06-01 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,C1428BCX,"(nan, nan)"
64,NaN,NaN,65.0,PACHA,COSTANERA\n Y PAMPA,sin nº,COSTANERA\n Y PAMPA,30712/05,1942 personas,"""C""",...,NaN,105,2010-08-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"(nan, nan)"
75,NaN,NaN,76.0,DORSIA,A. MOREAU \nDE JUSTO,2092,A. MOREAU \nDE JUSTO 2092,24150733/19,679 personas,"""C""",...,NaN,83,2010-06-18 00:00:00,2019-08-06,2019-11-10,NaN,Comuna 1,1107.0,C1107AFP,"(nan, nan)"
76,NaN,NaN,77.0,LA MADELEINE,A. MOREAU\n DE JUSTO,102/112,A. MOREAU\n DE JUSTO 102,80621/05,205 personas,"""C.C""",...,NaN,75,2006-06-01 00:00:00,NaN,NaN,Puerto Madero,Comuna 1,1107.0,C1107AAD,"(nan, nan)"
77,NaN,NaN,78.0,LA CITY,AV. ALVAREZ \nTHOMAS,1391/93,AV. ALVAREZ \nTHOMAS 1391,29275034/19,940 personas,"""C""",...,NaN,85,2006-06-23 00:00:00,2019-09-27,2019-12-28,Villa Ortuzar,Comuna 15,1427.0,C1427CDA,"(nan, nan)"
82,NaN,NaN,83.0,LO DE CELIA,HUMBERTO \nPRIMO,1783 1°P,HUMBERTO \nPRIMO 1783,22159527/17,150 personas,"""C.C""",...,NaN,123,2006-11-02 00:00:00,NaN,NaN,Constitucion,Comuna 1,1103.0,C1103ADI,"(nan, nan)"
83,NaN,NaN,84.0,CONTRAMANO,RODRIGUEZ \nPEÑA,1082 PB,RODRIGUEZ \nPEÑA 1082,26552605/17,335 personas,C C,...,NaN,56,2007-04-23 00:00:00,NaN,NaN,Recoleta,Comuna 2,1020.0,C1020ADV,"(nan, nan)"
91,NaN,NaN,92.0,JET,AV. RAFAEL \nOBLIGADO,4801,AV. RAFAEL \nOBLIGADO 4801,83133/05,688 personas,C,...,NaN,109,2008-12-19 00:00:00,2019-12-18,2020-03-22,Palermo,Comuna 14,1428.0,NaN,"(nan, nan)"
96,NaN,NaN,97.0,PRIVILEGE BA,AV. RAFAEL \nOBLIGADO,1221,AV. RAFAEL \nOBLIGADO 1221,47762/07,2966 personas,"""C""",...,NaN,526,2008-02-20 00:00:00,NaN,NaN,Palermo,Comuna 14,1425.0,NaN,"(nan, nan)"
97,NaN,NaN,98.0,MORENA DISCO,AV. JUAN B. \nALBERDI,2829/39,AV. JUAN B. \nALBERDI 2829,12206667/19,504 personas,"""C""",...,NaN,86,2008-09-04 00:00:00,2019-11-07,2020-01-27,Flores,Comuna 7,1406.0,C1406GSE,"(nan, nan)"
98,NaN,NaN,99.0,VOX,AV. HIPÓLITO\n YRIGOYEN,968,AV. HIPÓLITO\n YRIGOYEN 968,4720241/18,532 personas,"""C""",...,NaN,94,2008-11-07 00:00:00,2019-12-02,2020-03-03,Monserrat,Comuna 1,1086.0,C1086AAP,"(nan, nan)"
106,NaN,NaN,107.0,CIRCUS,AV. HIPÓLITO\n YRIGOYEN,947,AV. HIPÓLITO\n YRIGOYEN 947,22284096/19,400 poersonas,"""C""",...,NaN,70,2009-06-19 00:00:00,2019-12-05,2020-03-03,Monserrat,Comuna 1,1086.0,C1086AAO,"(nan, nan)"
109,NaN,NaN,110.0,TEQUILA,AV. RAFAEL \nOBLIGADO,6211,AV. RAFAEL \nOBLIGADO 6211,25674347/19,335 personas,"""C""",...,NaN,118,2010-10-15 00:00:00,2019-07-17,2019-09-22,Belgrano,Comuna 13,1428.0,NaN,"(nan, nan)"
110,NaN,NaN,111.0,MAGNOLIA,A. MOREAU \nDE JUSTO,1007,A. MOREAU \nDE JUSTO 1007,1082617/09,100 personas,"""C.C""",...,NaN,95,2009-10-23 00:00:00,NaN,NaN,Puerto Madero,Comuna 1,1107.0,C1107AAU,"(nan, nan)"
113,NaN,NaN,114.0,MÓDENA DESIGN,FIGUEROA \nALCORTA,2270,FIGUEROA \nALCORTA 2270,48.226/09.,581 personas,"""C""",...,NaN,116,2009-12-30 00:00:00,NaN,NaN,Recoleta,Comuna 2,1425.0,C1425CKO,"(nan, nan)"
114,NaN,NaN,115.0,HIPOLITO CLUB,HIPOLITO\n YRIGOYEN,847/8,HIPOLITO\n YRIGOYEN 847,18225/10,958 personas,"""C""",...,NaN,4,2010-01-15 00:00:00,NaN,NaN,Monserrat,Comuna 1,1086.0,C1086AAM,"(nan, nan)"
119,NaN,NaN,120.0,TERRAZAS \nDEL ESTE,R. OBLIGADO \nY SARMIENTO,NaN,R. OBLIGADO \nY SARMIENTO,36083286/2019,3095 personas,"""C""",...,,118,2016-12-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"(nan, nan)"
125,NaN,NaN,125.0,PIZZA BANANA,AV. RAFAEL \nOBLIGADO,6201,AV. RAFAEL \nOBLIGADO 6201,736109/11,1143 personas,"""C""",...,NaN,68,2011-05-20 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,NaN,"(nan, nan)"
150,NaN,NaN,150.0,JET,AV. RAFAEL \nOBLIGADO,4801,AV. RAFAEL \nOBLIGADO 4801,28901114/19,602 personas,C,...,NaN,87,2019-10-03 00:00:00,2019-12-18,2020-03-22,Palermo,Comuna 14,1428.0,NaN,"(nan, nan)"
152,NaN,NaN,152.0,NIX PREVIUS,HIPOLITO\n YRIGOYEN,847/8,HIPOLITO\n YRIGOYEN 847,25827534/17,342 personas,C,...,NaN,113,2016-11-25 00:00:00,NaN,NaN,Monserrat,Comuna 1,1086.0,C1086AAM,"(nan, nan)"
154,NaN,NaN,154.0,BRANDY,AV. RAFAEL \nOBLIGADO,6920,AV. RAFAEL \nOBLIGADO 6920,22314831/19,394 personas,C,...,NaN,70,2017-07-21 00:00:00,2019-11-29,2019-12-22,Belgrano,Comuna 13,1428.0,C1428EIV,"(nan, nan)"
156,NaN,NaN,156.0,ROSE IN RIO,AV. RAFAEL \nOBLIGADO,1221,AV. RAFAEL \nOBLIGADO 1221,23383908/19,1195 personas,C,...,NaN,101,2017-10-25 00:00:00,2019-12-13,2020-02-13,Palermo,Comuna 14,1425.0,NaN,"(nan, nan)"
159,NaN,NaN,159.0,BNN(BANANA),AV. RAFAEL \nOBLIGADO,6201,AV. RAFAEL \nOBLIGADO 6201,10450369/19,956 personas,C,...,NaN,48,2018-04-13 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,NaN,"(nan, nan)"

In [306]:
# ¿Cómo imputar los missing de las columnas "longitud" y "latitud"?
#      Investigar en google maps la ubicación del boliche y copiar las coordenadas
#      Crear un diccionario con el nombre del lugar y las coordenadas (respetando el orden latitud-longitud)
#               Ej: {'XEL - HA' : '(-34.59287390837825, -58.50793450348261)'}

In [307]:
#finalmente decidimos eliminar columna 'capacidad_personas' porque nos pareció irrelevante para nuestro trabajo
locales_bailables_1.drop(['capacidad_personas'], axis='columns', inplace=True)
locales_bailables_1

,numero_registro,direccion_normalizada,lat-lon
0,1.0,RIOBAMBA 345,"(-34.605027, -58.39375)"
1,2.0,ESMERALDA 1040,"(-34.596003, -58.37851)"
2,3.0,PERU 342,"(-34.612002000000004, -58.374727)"
3,4.0,SARMIENTO 1656,"(-34.605531, -58.390154)"
4,5.0,LAVALLE 343,"(-34.60195, -58.371747)"
...,...,...,...
156,156.0,AV. RAFAEL \nOBLIGADO 1221,"(nan, nan)"
157,157.0,AV. JUAN B. JUSTO 1579,"(-34.585813, -58.435554)"
158,158.0,AV. RIVADAVIA 10919,"(-34.639008000000004, -58.517858999999994)"
159,159.0,AV. RAFAEL \nOBLIGADO 6201,"(nan, nan)"
160,160.0,AV. CORDOBA 5208,"(-34.59016, -58.436476)"

In [312]:
locales_bailables[mask_lb_null]

,longitud,latitud,numero_registro,nombre,calle,numero,direccion_normalizada,numero_expediente,capacidad,clase,...,fecha_disposicion_de_rechazo,numero_disposicion_de_recalculo_capacidad,fecha_disposicion_de_capacidad,fecha_de_entrega_nueva_revalida,vencimiento,barrio,comuna,codigo_postal,codigo_postal_argentino,lat-lon
10,NaN,NaN,11.0,XEL - HA,AV SAN M ARTÍN,6628,AV SAN M ARTÍN 6628,6128100/19,692 personas,"""C""",...,NaN,70,2005-06-10 00:00:00,2019-11-20,2020-02-10,Villa Devoto,Comuna 11,1419.0,C1419ICQ,"(nan, nan)"
37,NaN,NaN,38.0,CAIX,R. OBLIGADO \nY SALGUERO,sin nº,R. OBLIGADO \nY SALGUERO,4960926/19,1764 personas,"""C""",...,NaN,134,2005-09-28 00:00:00,2019-11-14,2020-02-15,NaN,NaN,NaN,NaN,"(nan, nan)"
43,NaN,NaN,44.0,MANDARINE,R. OBLIGADO \nY SARMIENTO,sin nº,R. OBLIGADO \nY SARMIENTO,2335460/19,1613 personas,"""C""",...,NaN,38,2009-03-23 00:00:00,2019-11-22,2020-02-21,NaN,NaN,NaN,NaN,"(nan, nan)"
54,NaN,NaN,55.0,CLUB 74,FIGUEROA \nALCORTA,7474,FIGUEROA \nALCORTA 7474,10836/05,180 personas,"""B""",...,NaN,76,2006-06-01 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,C1428BCX,"(nan, nan)"
64,NaN,NaN,65.0,PACHA,COSTANERA\n Y PAMPA,sin nº,COSTANERA\n Y PAMPA,30712/05,1942 personas,"""C""",...,NaN,105,2010-08-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"(nan, nan)"
75,NaN,NaN,76.0,DORSIA,A. MOREAU \nDE JUSTO,2092,A. MOREAU \nDE JUSTO 2092,24150733/19,679 personas,"""C""",...,NaN,83,2010-06-18 00:00:00,2019-08-06,2019-11-10,NaN,Comuna 1,1107.0,C1107AFP,"(nan, nan)"
76,NaN,NaN,77.0,LA MADELEINE,A. MOREAU\n DE JUSTO,102/112,A. MOREAU\n DE JUSTO 102,80621/05,205 personas,"""C.C""",...,NaN,75,2006-06-01 00:00:00,NaN,NaN,Puerto Madero,Comuna 1,1107.0,C1107AAD,"(nan, nan)"
77,NaN,NaN,78.0,LA CITY,AV. ALVAREZ \nTHOMAS,1391/93,AV. ALVAREZ \nTHOMAS 1391,29275034/19,940 personas,"""C""",...,NaN,85,2006-06-23 00:00:00,2019-09-27,2019-12-28,Villa Ortuzar,Comuna 15,1427.0,C1427CDA,"(nan, nan)"
82,NaN,NaN,83.0,LO DE CELIA,HUMBERTO \nPRIMO,1783 1°P,HUMBERTO \nPRIMO 1783,22159527/17,150 personas,"""C.C""",...,NaN,123,2006-11-02 00:00:00,NaN,NaN,Constitucion,Comuna 1,1103.0,C1103ADI,"(nan, nan)"
83,NaN,NaN,84.0,CONTRAMANO,RODRIGUEZ \nPEÑA,1082 PB,RODRIGUEZ \nPEÑA 1082,26552605/17,335 personas,C C,...,NaN,56,2007-04-23 00:00:00,NaN,NaN,Recoleta,Comuna 2,1020.0,C1020ADV,"(nan, nan)"
91,NaN,NaN,92.0,JET,AV. RAFAEL \nOBLIGADO,4801,AV. RAFAEL \nOBLIGADO 4801,83133/05,688 personas,C,...,NaN,109,2008-12-19 00:00:00,2019-12-18,2020-03-22,Palermo,Comuna 14,1428.0,NaN,"(nan, nan)"
96,NaN,NaN,97.0,PRIVILEGE BA,AV. RAFAEL \nOBLIGADO,1221,AV. RAFAEL \nOBLIGADO 1221,47762/07,2966 personas,"""C""",...,NaN,526,2008-02-20 00:00:00,NaN,NaN,Palermo,Comuna 14,1425.0,NaN,"(nan, nan)"
97,NaN,NaN,98.0,MORENA DISCO,AV. JUAN B. \nALBERDI,2829/39,AV. JUAN B. \nALBERDI 2829,12206667/19,504 personas,"""C""",...,NaN,86,2008-09-04 00:00:00,2019-11-07,2020-01-27,Flores,Comuna 7,1406.0,C1406GSE,"(nan, nan)"
98,NaN,NaN,99.0,VOX,AV. HIPÓLITO\n YRIGOYEN,968,AV. HIPÓLITO\n YRIGOYEN 968,4720241/18,532 personas,"""C""",...,NaN,94,2008-11-07 00:00:00,2019-12-02,2020-03-03,Monserrat,Comuna 1,1086.0,C1086AAP,"(nan, nan)"
106,NaN,NaN,107.0,CIRCUS,AV. HIPÓLITO\n YRIGOYEN,947,AV. HIPÓLITO\n YRIGOYEN 947,22284096/19,400 poersonas,"""C""",...,NaN,70,2009-06-19 00:00:00,2019-12-05,2020-03-03,Monserrat,Comuna 1,1086.0,C1086AAO,"(nan, nan)"
109,NaN,NaN,110.0,TEQUILA,AV. RAFAEL \nOBLIGADO,6211,AV. RAFAEL \nOBLIGADO 6211,25674347/19,335 personas,"""C""",...,NaN,118,2010-10-15 00:00:00,2019-07-17,2019-09-22,Belgrano,Comuna 13,1428.0,NaN,"(nan, nan)"
110,NaN,NaN,111.0,MAGNOLIA,A. MOREAU \nDE JUSTO,1007,A. MOREAU \nDE JUSTO 1007,1082617/09,100 personas,"""C.C""",...,NaN,95,2009-10-23 00:00:00,NaN,NaN,Puerto Madero,Comuna 1,1107.0,C1107AAU,"(nan, nan)"
113,NaN,NaN,114.0,MÓDENA DESIGN,FIGUEROA \nALCORTA,2270,FIGUEROA \nALCORTA 2270,48.226/09.,581 personas,"""C""",...,NaN,116,2009-12-30 00:00:00,NaN,NaN,Recoleta,Comuna 2,1425.0,C1425CKO,"(nan, nan)"
114,NaN,NaN,115.0,HIPOLITO CLUB,HIPOLITO\n YRIGOYEN,847/8,HIPOLITO\n YRIGOYEN 847,18225/10,958 personas,"""C""",...,NaN,4,2010-01-15 00:00:00,NaN,NaN,Monserrat,Comuna 1,1086.0,C1086AAM,"(nan, nan)"
119,NaN,NaN,120.0,TERRAZAS \nDEL ESTE,R. OBLIGADO \nY SARMIENTO,NaN,R. OBLIGADO \nY SARMIENTO,36083286/2019,3095 personas,"""C""",...,,118,2016-12-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"(nan, nan)"
125,NaN,NaN,125.0,PIZZA BANANA,AV. RAFAEL \nOBLIGADO,6201,AV. RAFAEL \nOBLIGADO 6201,736109/11,1143 personas,"""C""",...,NaN,68,2011-05-20 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,NaN,"(nan, nan)"
150,NaN,NaN,150.0,JET,AV. RAFAEL \nOBLIGADO,4801,AV. RAFAEL \nOBLIGADO 4801,28901114/19,602 personas,C,...,NaN,87,2019-10-03 00:00:00,2019-12-18,2020-03-22,Palermo,Comuna 14,1428.0,NaN,"(nan, nan)"
152,NaN,NaN,152.0,NIX PREVIUS,HIPOLITO\n YRIGOYEN,847/8,HIPOLITO\n YRIGOYEN 847,25827534/17,342 personas,C,...,NaN,113,2016-11-25 00:00:00,NaN,NaN,Monserrat,Comuna 1,1086.0,C1086AAM,"(nan, nan)"
154,NaN,NaN,154.0,BRANDY,AV. RAFAEL \nOBLIGADO,6920,AV. RAFAEL \nOBLIGADO 6920,22314831/19,394 personas,C,...,NaN,70,2017-07-21 00:00:00,2019-11-29,2019-12-22,Belgrano,Comuna 13,1428.0,C1428EIV,"(nan, nan)"
156,NaN,NaN,156.0,ROSE IN RIO,AV. RAFAEL \nOBLIGADO,1221,AV. RAFAEL \nOBLIGADO 1221,23383908/19,1195 personas,C,...,NaN,101,2017-10-25 00:00:00,2019-12-13,2020-02-13,Palermo,Comuna 14,1425.0,NaN,"(nan, nan)"
159,NaN,NaN,159.0,BNN(BANANA),AV. RAFAEL \nOBLIGADO,6201,AV. RAFAEL \nOBLIGADO 6201,10450369/19,956 personas,C,...,NaN,48,2018-04-13 00:00:00,NaN,NaN,Belgrano,Comuna 13,1428.0,NaN,"(nan, nan)"